package service

import (
	"net/url"
	"strings"
)

var brandPresets map[string]string

func init() {
	brandPresets = make(map[string]string)

	// ========== 搜索引擎 ==========
	brandPresets["baidu.com"] = "/static/icons/engine/baidu.svg"
	brandPresets["bing.com"] = "/static/icons/engine/bing.svg"
	brandPresets["duckduckgo.com"] = "/static/icons/engine/DuckDuckGo.svg"
	brandPresets["duck.com"] = "/static/icons/engine/DuckDuckGo.svg"
	brandPresets["google.com"] = "/static/icons/engine/google.svg"
	brandPresets["google.cn"] = "/static/icons/engine/google.svg"
	brandPresets["google.com.hk"] = "/static/icons/engine/google.svg"
	brandPresets["so.360.cn"] = "/static/icons/engine/360.svg"
	brandPresets["360.cn"] = "/static/icons/engine/360.svg"
	brandPresets["haosou.com"] = "/static/icons/engine/360.svg"
	brandPresets["sogou.com"] = "/static/icons/engine/sougou.svg"

	// ========== AI 服务 ==========
	brandPresets["anthropic.com"] = "/static/icons/brand/anthropic.svg"
	brandPresets["claude.ai"] = "/static/icons/brand/anthropic.svg"
	brandPresets["huggingface.co"] = "/static/icons/brand/huggingface.svg"

	// ========== 国际品牌 ==========
	brandPresets["airbnb.com"] = "/static/icons/brand/airbnb.svg"
	brandPresets["airbnb.cn"] = "/static/icons/brand/airbnb.svg"
	brandPresets["algolia.com"] = "/static/icons/brand/algolia.svg"
	brandPresets["algolia.net"] = "/static/icons/brand/algolia.svg"
	brandPresets["amazon.com"] = "/static/icons/brand/amazon.svg"
	brandPresets["amazon.cn"] = "/static/icons/brand/amazon.svg"
	brandPresets["amazon.co.jp"] = "/static/icons/brand/amazon.svg"
	brandPresets["amazonaws.com"] = "/static/icons/brand/amazon.svg"
	brandPresets["aws.amazon.com"] = "/static/icons/brand/amazon.svg"
	brandPresets["apple.com"] = "/static/icons/brand/apple.svg"
	brandPresets["icloud.com"] = "/static/icons/brand/apple.svg"
	brandPresets["developer.apple.com"] = "/static/icons/brand/apple.svg"
	brandPresets["artstation.com"] = "/static/icons/brand/artstation.svg"
	brandPresets["asana.com"] = "/static/icons/brand/asana.svg"
	brandPresets["behance.net"] = "/static/icons/brand/behance.svg"
	brandPresets["bitbucket.org"] = "/static/icons/brand/bitbucket.svg"
	brandPresets["booking.com"] = "/static/icons/brand/booking.svg"
	brandPresets["box.com"] = "/static/icons/brand/box.svg"
	brandPresets["clickup.com"] = "/static/icons/brand/clickup.svg"
	brandPresets["cloudflare.com"] = "/static/icons/brand/cloudflare.svg"
	brandPresets["workers.cloudflare.com"] = "/static/icons/brand/cloudflare.svg"
	brandPresets["cloudinary.com"] = "/static/icons/brand/cloudinary.svg"
	brandPresets["codesandbox.io"] = "/static/icons/brand/codesandbox.svg"
	brandPresets["codepen.io"] = "/static/icons/brand/codepen.svg"
	brandPresets["confluence.atlassian.net"] = "/static/icons/brand/confluence.svg"
	brandPresets["atlassian.com"] = "/static/icons/brand/confluence.svg"
	brandPresets["crowdin.com"] = "/static/icons/brand/crowdin.svg"
	brandPresets["dailymotion.com"] = "/static/icons/brand/dailymotion.svg"
	brandPresets["deepl.com"] = "/static/icons/brand/deepl.svg"
	brandPresets["dev.to"] = "/static/icons/brand/devdotto.svg"
	brandPresets["deviantart.com"] = "/static/icons/brand/deviantart.svg"
	brandPresets["discord.com"] = "/static/icons/brand/discord.svg"
	brandPresets["discord.gg"] = "/static/icons/brand/discord.svg"
	brandPresets["doordash.com"] = "/static/icons/brand/doordash.svg"
	brandPresets["dribbble.com"] = "/static/icons/brand/dribbble.svg"
	brandPresets["dropbox.com"] = "/static/icons/brand/dropbox.svg"
	brandPresets["element.io"] = "/static/icons/brand/element.svg"
	brandPresets["app.element.io"] = "/static/icons/brand/element.svg"
	brandPresets["evernote.com"] = "/static/icons/brand/evernote.svg"
	brandPresets["etsy.com"] = "/static/icons/brand/etsy.svg"
	brandPresets["feedly.com"] = "/static/icons/brand/feedly.svg"
	brandPresets["figma.com"] = "/static/icons/brand/figma.svg"
	brandPresets["flickr.com"] = "/static/icons/brand/flickr.svg"
	brandPresets["flipboard.com"] = "/static/icons/brand/flipboard.svg"
	brandPresets["500px.com"] = "/static/icons/brand/500px.svg"
	brandPresets["github.com"] = "/static/icons/brand/github.svg"
	brandPresets["gitlab.com"] = "/static/icons/brand/gitlab.svg"
	brandPresets["goodreads.com"] = "/static/icons/brand/goodreads.svg"
	brandPresets["grammarly.com"] = "/static/icons/brand/grammarly.svg"
	brandPresets["gumroad.com"] = "/static/icons/brand/gumroad.svg"
	brandPresets["hackernews.com"] = "/static/icons/brand/hackernews.svg"
	brandPresets["news.ycombinator.com"] = "/static/icons/brand/hackernews.svg"
	brandPresets["hubspot.com"] = "/static/icons/brand/hubspot.svg"
	brandPresets["imdb.com"] = "/static/icons/brand/imdb.svg"
	brandPresets["instagram.com"] = "/static/icons/brand/instagram.svg"
	brandPresets["intercom.com"] = "/static/icons/brand/intercom.svg"
	brandPresets["intercom.help"] = "/static/icons/brand/intercom.svg"
	brandPresets["jira.atlassian.net"] = "/static/icons/brand/jira.svg"
	brandPresets["jira.com"] = "/static/icons/brand/jira.svg"
	brandPresets["kick.com"] = "/static/icons/brand/kick.svg"
	brandPresets["last.fm"] = "/static/icons/brand/lastdotfm.svg"
	brandPresets["lastfm.com"] = "/static/icons/brand/lastdotfm.svg"
	brandPresets["lemonsqueezy.com"] = "/static/icons/brand/lemonsqueezy.svg"
	brandPresets["letterboxd.com"] = "/static/icons/brand/letterboxd.svg"
	brandPresets["lichess.org"] = "/static/icons/brand/lichess.svg"
	brandPresets["linear.app"] = "/static/icons/brand/linear.svg"
	brandPresets["mailchimp.com"] = "/static/icons/brand/mailchimp.svg"
	brandPresets["matrix.org"] = "/static/icons/brand/matrix.svg"
	brandPresets["matrix.to"] = "/static/icons/brand/matrix.svg"
	brandPresets["mattermost.com"] = "/static/icons/brand/mattermost.svg"
	brandPresets["mattermost.org"] = "/static/icons/brand/mattermost.svg"
	brandPresets["medium.com"] = "/static/icons/brand/medium.svg"
	brandPresets["meilisearch.com"] = "/static/icons/brand/meilisearch.svg"
	brandPresets["meta.com"] = "/static/icons/brand/meta.svg"
	brandPresets["facebook.com"] = "/static/icons/brand/meta.svg"
	brandPresets["fb.com"] = "/static/icons/brand/meta.svg"
	brandPresets["fbcdn.net"] = "/static/icons/brand/meta.svg"
	brandPresets["m.facebook.com"] = "/static/icons/brand/meta.svg"
	brandPresets["microsoft.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["office.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["outlook.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["live.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["onenote.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["sharepoint.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["teams.microsoft.com"] = "/static/icons/brand/microsoft.svg"
	brandPresets["naver.com"] = "/static/icons/brand/naver.svg"
	brandPresets["naver.me"] = "/static/icons/brand/naver.svg"
	brandPresets["netflix.com"] = "/static/icons/brand/netflix.svg"
	brandPresets["netlify.com"] = "/static/icons/brand/netlify.svg"
	brandPresets["notion.so"] = "/static/icons/brand/notion.svg"
	brandPresets["notion.site"] = "/static/icons/brand/notion.svg"
	brandPresets["obsidian.md"] = "/static/icons/brand/obsidian.svg"
	brandPresets["patreon.com"] = "/static/icons/brand/patreon.svg"
	brandPresets["paypal.com"] = "/static/icons/brand/paypal.svg"
	brandPresets["paypal.me"] = "/static/icons/brand/paypal.svg"
	brandPresets["pinterest.com"] = "/static/icons/brand/pinterest.svg"
	brandPresets["pin.it"] = "/static/icons/brand/pinterest.svg"
	brandPresets["pixabay.com"] = "/static/icons/brand/pixabay.svg"
	brandPresets["producthunt.com"] = "/static/icons/brand/producthunt.svg"
	brandPresets["reddit.com"] = "/static/icons/brand/reddit.svg"
	brandPresets["old.reddit.com"] = "/static/icons/brand/reddit.svg"
	brandPresets["new.reddit.com"] = "/static/icons/brand/reddit.svg"
	brandPresets["replit.com"] = "/static/icons/brand/replit.svg"
	brandPresets["repl.it"] = "/static/icons/brand/replit.svg"
	brandPresets["rottentomatoes.com"] = "/static/icons/brand/rottentomatoes.svg"
	brandPresets["rumble.com"] = "/static/icons/brand/rumble.svg"
	brandPresets["runkeeper.com"] = "/static/icons/brand/runkeeper.svg"
	brandPresets["salesforce.com"] = "/static/icons/brand/salesforce.svg"
	brandPresets["force.com"] = "/static/icons/brand/salesforce.svg"
	brandPresets["shopify.com"] = "/static/icons/brand/shopify.svg"
	brandPresets["myshopify.com"] = "/static/icons/brand/shopify.svg"
	brandPresets["sketch.com"] = "/static/icons/brand/sketch.svg"
	brandPresets["slack.com"] = "/static/icons/brand/slack.svg"
	brandPresets["snapchat.com"] = "/static/icons/brand/snapchat.svg"
	brandPresets["soundcloud.com"] = "/static/icons/brand/soundcloud.svg"
	brandPresets["spotify.com"] = "/static/icons/brand/spotify.svg"
	brandPresets["open.spotify.com"] = "/static/icons/brand/spotify.svg"
	brandPresets["squarespace.com"] = "/static/icons/brand/squarespace.svg"
	brandPresets["stackoverflow.com"] = "/static/icons/brand/stackoverflow.svg"
	brandPresets["steamcommunity.com"] = "/static/icons/brand/steam.svg"
	brandPresets["store.steampowered.com"] = "/static/icons/brand/steam.svg"
	brandPresets["steampowered.com"] = "/static/icons/brand/steam.svg"
	brandPresets["strava.com"] = "/static/icons/brand/strava.svg"
	brandPresets["stripe.com"] = "/static/icons/brand/stripe.svg"
	brandPresets["telegram.org"] = "/static/icons/brand/telegram.svg"
	brandPresets["t.me"] = "/static/icons/brand/telegram.svg"
	brandPresets["web.telegram.org"] = "/static/icons/brand/telegram.svg"
	brandPresets["trello.com"] = "/static/icons/brand/trello.svg"
	brandPresets["tripadvisor.com"] = "/static/icons/brand/tripadvisor.svg"
	brandPresets["tripadvisor.cn"] = "/static/icons/brand/tripadvisor.svg"
	brandPresets["tumblr.com"] = "/static/icons/brand/tumblr.svg"
	brandPresets["twitch.tv"] = "/static/icons/brand/twitch.svg"
	brandPresets["twitter.com"] = "/static/icons/brand/twitter.svg"
	brandPresets["x.com"] = "/static/icons/brand/twitter.svg"
	brandPresets["t.co"] = "/static/icons/brand/twitter.svg"
	brandPresets["ubereats.com"] = "/static/icons/brand/ubereats.svg"
	brandPresets["uber.com"] = "/static/icons/brand/ubereats.svg"
	brandPresets["unsplash.com"] = "/static/icons/brand/unsplash.svg"
	brandPresets["vercel.com"] = "/static/icons/brand/vercel.svg"
	brandPresets["vercel.app"] = "/static/icons/brand/vercel.svg"
	brandPresets["now.sh"] = "/static/icons/brand/vercel.svg"
	brandPresets["webflow.com"] = "/static/icons/brand/webflow.svg"
	brandPresets["wikipedia.org"] = "/static/icons/brand/wikipedia.svg"
	brandPresets["wikimedia.org"] = "/static/icons/brand/wikipedia.svg"
	brandPresets["zh.wikipedia.org"] = "/static/icons/brand/wikipedia.svg"
	brandPresets["en.wikipedia.org"] = "/static/icons/brand/wikipedia.svg"
	brandPresets["wix.com"] = "/static/icons/brand/wix.svg"
	brandPresets["wordpress.com"] = "/static/icons/brand/wordpress.svg"
	brandPresets["wordpress.org"] = "/static/icons/brand/wordpress.svg"
	brandPresets["wp.com"] = "/static/icons/brand/wordpress.svg"
	brandPresets["youtube.com"] = "/static/icons/brand/youtube.svg"
	brandPresets["youtu.be"] = "/static/icons/brand/youtube.svg"
	brandPresets["zendesk.com"] = "/static/icons/brand/zendesk.svg"
	brandPresets["zulip.com"] = "/static/icons/brand/zulip.svg"
	brandPresets["zulipchat.com"] = "/static/icons/brand/zulip.svg"
	brandPresets["aliexpress.com"] = "/static/icons/brand/aliexpress.svg"
	brandPresets["aliexpress.ru"] = "/static/icons/brand/aliexpress.svg"
	brandPresets["bandcamp.com"] = "/static/icons/brand/bandcamp.svg"
	brandPresets["buymeacoffee.com"] = "/static/icons/brand/buymeacoffee.svg"
	brandPresets["chess.com"] = "/static/icons/brand/chessdotcom.svg"
	brandPresets["epicgames.com"] = "/static/icons/brand/epicgames.svg"
	brandPresets["epicgames.store"] = "/static/icons/brand/epicgames.svg"
	brandPresets["ko-fi.com"] = "/static/icons/brand/ko-fi.svg"
	brandPresets["opencollective.com"] = "/static/icons/brand/opencollective.svg"
	brandPresets["playstation.com"] = "/static/icons/brand/playstation.svg"
	brandPresets["signal.org"] = "/static/icons/brand/signal.svg"
	brandPresets["signal.me"] = "/static/icons/brand/signal.svg"
	brandPresets["whatsapp.com"] = "/static/icons/brand/whatsapp.svg"
	brandPresets["web.whatsapp.com"] = "/static/icons/brand/whatsapp.svg"
	brandPresets["wa.me"] = "/static/icons/brand/whatsapp.svg"
	brandPresets["zoom.us"] = "/static/icons/brand/zoom.svg"

	// ========== 中国品牌 ==========
	brandPresets["aliyun.com"] = "/static/icons/brand/aliyun.svg"
	brandPresets["alibaba.com"] = "/static/icons/brand/aliyun.svg"
	brandPresets["alibabacloud.com"] = "/static/icons/brand/aliyun.svg"
	brandPresets["bilibili.com"] = "/static/icons/brand/bilibili.svg"
	brandPresets["bytedance.com"] = "/static/icons/brand/bytedance.svg"
	brandPresets["byted.org"] = "/static/icons/brand/bytedance.svg"
	brandPresets["cloud.tencent.com"] = "/static/icons/brand/tencentcloud.png"
	brandPresets["tencent.com"] = "/static/icons/brand/tencentcloud.png"
	brandPresets["csdn.net"] = "/static/icons/brand/csdn.svg"
	brandPresets["douyin.com"] = "/static/icons/brand/douyin.svg"
	brandPresets["douban.com"] = "/static/icons/brand/douban.svg"
	brandPresets["book.douban.com"] = "/static/icons/brand/douban.svg"
	brandPresets["movie.douban.com"] = "/static/icons/brand/douban.svg"
	brandPresets["music.douban.com"] = "/static/icons/brand/douban.svg"
	brandPresets["gitee.com"] = "/static/icons/brand/gitee.svg"
	brandPresets["huawei.com"] = "/static/icons/brand/huawei.svg"
	brandPresets["huaweicloud.com"] = "/static/icons/brand/huawei.svg"
	brandPresets["iqiyi.com"] = "/static/icons/brand/iqy.svg"
	brandPresets["jdcloud.com"] = "/static/icons/brand/jingdongyun.svg"
	brandPresets["jd.com"] = "/static/icons/brand/jingdongyun.svg"
	brandPresets["js.design"] = "/static/icons/brand/jsdesign.svg"
	brandPresets["juejin.cn"] = "/static/icons/brand/juejin.svg"
	brandPresets["juejin.im"] = "/static/icons/brand/juejin.svg"
	brandPresets["kuaishou.com"] = "/static/icons/brand/kuaishou.svg"
	brandPresets["le.com"] = "/static/icons/brand/leshi.svg"
	brandPresets["lenovo.com"] = "/static/icons/brand/lenovo.svg"
	brandPresets["lenovomm.com"] = "/static/icons/brand/lenovo.svg"
	brandPresets["meituan.com"] = "/static/icons/brand/meituan.svg"
	brandPresets["meishi.meituan.com"] = "/static/icons/brand/meituan.svg"
	brandPresets["meizu.com"] = "/static/icons/brand/meizu.svg"
	brandPresets["mgtv.com"] = "/static/icons/brand/mangguo.svg"
	brandPresets["migu.cn"] = "/static/icons/brand/migu.svg"
	brandPresets["music.163.com"] = "/static/icons/brand/wangyiyun.svg"
	brandPresets["163.com"] = "/static/icons/brand/wangyiyun.svg"
	brandPresets["xiaohongshu.com"] = "/static/icons/brand/xiaohongshu.svg"
	brandPresets["xhslink.com"] = "/static/icons/brand/xiaohongshu.svg"
	brandPresets["xiaomi.com"] = "/static/icons/brand/xiaomi.svg"
	brandPresets["mi.com"] = "/static/icons/brand/xiaomi.svg"
	brandPresets["xiaomiyoupin.com"] = "/static/icons/brand/xiaomi.svg"
	brandPresets["zhihu.com"] = "/static/icons/brand/zhihu.svg"
	brandPresets["zhuanlan.zhihu.com"] = "/static/icons/brand/zhihu.svg"
	brandPresets["oppo.com"] = "/static/icons/brand/oppo.svg"
	brandPresets["coloros.com"] = "/static/icons/brand/oppo.svg"
	brandPresets["oppoer.com"] = "/static/icons/brand/oppo.svg"
	brandPresets["vivo.com"] = "/static/icons/brand/vivo.svg"
	brandPresets["vivo.com.cn"] = "/static/icons/brand/vivo.svg"
	brandPresets["oneplus.com"] = "/static/icons/brand/oneplus.svg"
	brandPresets["oneplus.cn"] = "/static/icons/brand/oneplus.svg"
	brandPresets["taobao.com"] = "/static/icons/brand/taobao.svg"
	brandPresets["tmall.com"] = "/static/icons/brand/taobao.svg"
	brandPresets["taobao.org"] = "/static/icons/brand/taobao.svg"
	brandPresets["tiktok.com"] = "/static/icons/brand/tiktok.svg"
	brandPresets["tiktokv.com"] = "/static/icons/brand/tiktok.svg"
	brandPresets["qq.com"] = "/static/icons/brand/qq_symbol.png"
	brandPresets["v.qq.com"] = "/static/icons/brand/qq_symbol.png"
	brandPresets["y.qq.com"] = "/static/icons/brand/qq_symbol.png"
	brandPresets["weibo.com"] = "/static/icons/brand/weibo.svg"
	brandPresets["weibo.cn"] = "/static/icons/brand/weibo.svg"
	brandPresets["weixin.qq.com"] = "/static/icons/brand/weixin.svg"
	brandPresets["wx.qq.com"] = "/static/icons/brand/weixin.svg"
	brandPresets["wechat.com"] = "/static/icons/brand/weixin.svg"
	brandPresets["mp.weixin.qq.com"] = "/static/icons/brand/weixin.svg"
	brandPresets["youku.com"] = "/static/icons/brand/youku.svg"
	brandPresets["acfun.cn"] = "/static/icons/brand/acfun.svg"
	brandPresets["pan.baidu.com"] = "/static/icons/brand/baiduyun.svg"
	// Note: baidu.com is already mapped to the search engine icon above; skip duplicate
	brandPresets["baidubce.com"] = "/static/icons/brand/baiduyun.svg"
	brandPresets["tianyancha.com"] = "/static/icons/brand/tsy.png"
	brandPresets["volcengine.com"] = "/static/icons/brand/huoshanfanyi.png"
	brandPresets["imgurl.org"] = "/static/icons/brand/imgurl.png"
	brandPresets["mtab.cc"] = "/static/icons/brand/mtab.png"
	brandPresets["onenav.com"] = "/static/icons/brand/onenav.png"
	brandPresets["onenav.cc"] = "/static/icons/brand/onenav.png"

	// ========== 开发者工具 ==========
	brandPresets["ansible.com"] = "/static/icons/brand/ansible.svg"
	brandPresets["auth0.com"] = "/static/icons/brand/auth0.svg"
	brandPresets["circleci.com"] = "/static/icons/brand/circleci.svg"
	brandPresets["consul.io"] = "/static/icons/brand/consul.svg"
	brandPresets["consul.hashicorp.com"] = "/static/icons/brand/consul.svg"
	brandPresets["dart.dev"] = "/static/icons/brand/dart.svg"
	brandPresets["pub.dev"] = "/static/icons/brand/dart.svg"
	brandPresets["digitalocean.com"] = "/static/icons/brand/digitalocean.svg"
	brandPresets["docker.com"] = "/static/icons/brand/docker.svg"
	brandPresets["hub.docker.com"] = "/static/icons/brand/docker.svg"
	brandPresets["docs.docker.com"] = "/static/icons/brand/docker.svg"
	brandPresets["elasticsearch.org"] = "/static/icons/brand/elasticsearch.svg"
	brandPresets["elastic.co"] = "/static/icons/brand/elasticsearch.svg"
	brandPresets["firebase.google.com"] = "/static/icons/brand/firebase.svg"
	brandPresets["firebaseapp.com"] = "/static/icons/brand/firebase.svg"
	brandPresets["flutter.dev"] = "/static/icons/brand/flutter.svg"
	brandPresets["go.dev"] = "/static/icons/brand/go.svg"
	brandPresets["golang.org"] = "/static/icons/brand/go.svg"
	brandPresets["pkg.go.dev"] = "/static/icons/brand/go.svg"
	brandPresets["gradle.org"] = "/static/icons/brand/gradle.svg"
	brandPresets["docs.gradle.org"] = "/static/icons/brand/gradle.svg"
	brandPresets["grafana.com"] = "/static/icons/brand/grafana.svg"
	brandPresets["grafana.net"] = "/static/icons/brand/grafana.svg"
	brandPresets["helm.sh"] = "/static/icons/brand/helm.svg"
	brandPresets["hetzner.com"] = "/static/icons/brand/hetzner.svg"
	brandPresets["hetzner.cloud"] = "/static/icons/brand/hetzner.svg"
	brandPresets["jenkins.io"] = "/static/icons/brand/jenkins.svg"
	brandPresets["kafka.apache.org"] = "/static/icons/brand/kafka.svg"
	brandPresets["kotlinlang.org"] = "/static/icons/brand/kotlin.svg"
	brandPresets["kubernetes.io"] = "/static/icons/brand/kubernetes.svg"
	brandPresets["k8s.io"] = "/static/icons/brand/kubernetes.svg"
	brandPresets["airflow.apache.org"] = "/static/icons/brand/airflow.svg"
	brandPresets["spark.apache.org"] = "/static/icons/brand/spark.svg"
	brandPresets["hadoop.apache.org"] = "/static/icons/brand/hadoop.svg"
	brandPresets["maven.apache.org"] = "/static/icons/brand/maven.svg"
	brandPresets["linkedin.com"] = "/static/icons/brand/linkedin.svg"
	brandPresets["linode.com"] = "/static/icons/brand/linode.svg"
	brandPresets["linode.net"] = "/static/icons/brand/linode.svg"
	brandPresets["akamai.com"] = "/static/icons/brand/linode.svg"
	brandPresets["mongodb.com"] = "/static/icons/brand/mongodb.svg"
	brandPresets["mongodb.org"] = "/static/icons/brand/mongodb.svg"
	brandPresets["mongodb.net"] = "/static/icons/brand/mongodb.svg"
	brandPresets["cloud.mongodb.com"] = "/static/icons/brand/mongodb.svg"
	brandPresets["nginx.org"] = "/static/icons/brand/nginx.svg"
	brandPresets["nginx.com"] = "/static/icons/brand/nginx.svg"
	brandPresets["npmjs.com"] = "/static/icons/brand/npmjs.svg"
	brandPresets["npmjs.org"] = "/static/icons/brand/npmjs.svg"
	brandPresets["npm.im"] = "/static/icons/brand/npmjs.svg"
	brandPresets["ovh.com"] = "/static/icons/brand/ovh.svg"
	brandPresets["ovhcloud.com"] = "/static/icons/brand/ovh.svg"
	brandPresets["packagist.org"] = "/static/icons/brand/packagist.svg"
	brandPresets["packagist.com"] = "/static/icons/brand/packagist.svg"
	brandPresets["php.net"] = "/static/icons/brand/php.svg"
	brandPresets["postgresql.org"] = "/static/icons/brand/postgresql.svg"
	brandPresets["postgrespro.ru"] = "/static/icons/brand/postgresql.svg"
	brandPresets["prometheus.io"] = "/static/icons/brand/prometheus.svg"
	brandPresets["pypi.org"] = "/static/icons/brand/pypi.svg"
	brandPresets["pythonhosted.org"] = "/static/icons/brand/pypi.svg"
	brandPresets["python.org"] = "/static/icons/brand/python.svg"
	brandPresets["docs.python.org"] = "/static/icons/brand/python.svg"
	brandPresets["rabbitmq.com"] = "/static/icons/brand/rabbitmq.svg"
	brandPresets["rancher.com"] = "/static/icons/brand/rancher.svg"
	brandPresets["rancher.io"] = "/static/icons/brand/rancher.svg"
	brandPresets["redis.io"] = "/static/icons/brand/redis.svg"
	brandPresets["redis.com"] = "/static/icons/brand/redis.svg"
	brandPresets["redislabs.com"] = "/static/icons/brand/redis.svg"
	brandPresets["rubygems.org"] = "/static/icons/brand/rubygems.svg"
	brandPresets["rust-lang.org"] = "/static/icons/brand/rust.svg"
	brandPresets["crates.io"] = "/static/icons/brand/rust.svg"
	brandPresets["docs.rs"] = "/static/icons/brand/rust.svg"
	brandPresets["supabase.com"] = "/static/icons/brand/supabase.svg"
	brandPresets["supabase.co"] = "/static/icons/brand/supabase.svg"
	brandPresets["swift.org"] = "/static/icons/brand/swift.svg"
	brandPresets["developer.apple.com/swift"] = "/static/icons/brand/swift.svg"
	brandPresets["terraform.io"] = "/static/icons/brand/terraform.svg"
	brandPresets["hashicorp.com"] = "/static/icons/brand/terraform.svg"
	brandPresets["travis-ci.org"] = "/static/icons/brand/travisci.svg"
	brandPresets["travis-ci.com"] = "/static/icons/brand/travisci.svg"
	brandPresets["vaultproject.io"] = "/static/icons/brand/vault.svg"
	brandPresets["vault.hashicorp.com"] = "/static/icons/brand/vault.svg"
	brandPresets["vultr.com"] = "/static/icons/brand/vultr.svg"
	brandPresets["github.io"] = "/static/icons/brand/githubactions.svg"
	// Note: gitlab.com is mapped to GitLab above; the CI preset is kept for future CI-specific domains

	// ========== 开发语言/框架 ==========
	brandPresets["angular.io"] = "/static/icons/brand/angular.svg"
	brandPresets["angular.dev"] = "/static/icons/brand/angular.svg"
	brandPresets["astro.build"] = "/static/icons/brand/astro.svg"
	brandPresets["babeljs.io"] = "/static/icons/brand/babel.svg"
	brandPresets["getbootstrap.com"] = "/static/icons/brand/bootstrap.svg"
	brandPresets["bun.sh"] = "/static/icons/brand/bun.svg"
	brandPresets["chaijs.com"] = "/static/icons/brand/chai.svg"
	brandPresets["cypress.io"] = "/static/icons/brand/cypress.svg"
	brandPresets["deno.com"] = "/static/icons/brand/deno.svg"
	brandPresets["deno.land"] = "/static/icons/brand/deno.svg"
	brandPresets["drizzle.team"] = "/static/icons/brand/drizzle.svg"
	brandPresets["orm.drizzle.team"] = "/static/icons/brand/drizzle.svg"
	brandPresets["electronjs.org"] = "/static/icons/brand/electron.svg"
	brandPresets["esbuild.github.io"] = "/static/icons/brand/esbuild.svg"
	brandPresets["eslint.org"] = "/static/icons/brand/eslint.svg"
	brandPresets["gatsbyjs.com"] = "/static/icons/brand/gatsby.svg"
	brandPresets["gatsbyjs.org"] = "/static/icons/brand/gatsby.svg"
	brandPresets["graphql.org"] = "/static/icons/brand/graphql.svg"
	brandPresets["graphql.com"] = "/static/icons/brand/graphql.svg"
	brandPresets["jestjs.io"] = "/static/icons/brand/jest.svg"
	brandPresets["lesscss.org"] = "/static/icons/brand/less.svg"
	brandPresets["lxqt.me"] = "/static/icons/brand/linux.svg"
	brandPresets["linux.org"] = "/static/icons/brand/linux.svg"
	brandPresets["kernel.org"] = "/static/icons/brand/linux.svg"
	brandPresets["mochajs.org"] = "/static/icons/brand/mocha.svg"
	brandPresets["mobx.js.org"] = "/static/icons/brand/mobx.svg"
	brandPresets["nextjs.org"] = "/static/icons/brand/nextdotjs.svg"
	brandPresets["nextjs.test"] = "/static/icons/brand/nextdotjs.svg"
	brandPresets["nodejs.org"] = "/static/icons/brand/nodejs.svg"
	brandPresets["nodejs.com"] = "/static/icons/brand/nodejs.svg"
	brandPresets["nuxt.com"] = "/static/icons/brand/nuxtdotjs.svg"
	brandPresets["nuxtjs.org"] = "/static/icons/brand/nuxtdotjs.svg"
	brandPresets["postcss.org"] = "/static/icons/brand/postcss.svg"
	brandPresets["prisma.io"] = "/static/icons/brand/prisma.svg"
	brandPresets["react.dev"] = "/static/icons/brand/react.svg"
	brandPresets["reactjs.org"] = "/static/icons/brand/react.svg"
	brandPresets["legacy.reactjs.org"] = "/static/icons/brand/react.svg"
	brandPresets["redux.js.org"] = "/static/icons/brand/redux.svg"
	brandPresets["rollupjs.org"] = "/static/icons/brand/rollupdotjs.svg"
	brandPresets["rxjs.dev"] = "/static/icons/brand/rxjs.svg"
	brandPresets["sass-lang.com"] = "/static/icons/brand/sass.svg"
	brandPresets["solidjs.com"] = "/static/icons/brand/solid.svg"
	brandPresets["svelte.dev"] = "/static/icons/brand/svelte.svg"
	brandPresets["tailwindcss.com"] = "/static/icons/brand/tailwindcss.svg"
	brandPresets["trpc.io"] = "/static/icons/brand/trpc.svg"
	brandPresets["vitejs.dev"] = "/static/icons/brand/vite.svg"
	brandPresets["vite.dev"] = "/static/icons/brand/vite.svg"
	brandPresets["vuejs.org"] = "/static/icons/brand/vue.svg"
	brandPresets["vuejs.com"] = "/static/icons/brand/vue.svg"
	brandPresets["v3.vuejs.org"] = "/static/icons/brand/vue.svg"
	brandPresets["webpack.js.org"] = "/static/icons/brand/webpack.svg"
	brandPresets["remix.run"] = "/static/icons/brand/remix.svg"

	// ========== 操作系统/数据库 ==========
	brandPresets["archlinux.org"] = "/static/icons/brand/archlinux.svg"
	brandPresets["centos.org"] = "/static/icons/brand/centos.svg"
	brandPresets["debian.org"] = "/static/icons/brand/debian.svg"
	brandPresets["fedoraproject.org"] = "/static/icons/brand/fedora.svg"
	brandPresets["mariadb.org"] = "/static/icons/brand/mariadb.svg"
	brandPresets["mariadb.com"] = "/static/icons/brand/mariadb.svg"
	brandPresets["planetscale.com"] = "/static/icons/brand/planetscale.svg"
	brandPresets["sqlite.org"] = "/static/icons/brand/sqlite.svg"
	brandPresets["ubuntu.com"] = "/static/icons/brand/ubuntu.svg"
	// Note: developer.apple.com is mapped to Apple above; macOS preset uses macos.local
	brandPresets["macos.local"] = "/static/icons/brand/macos.svg"

	// ========== 版本控制/工具 ==========
	brandPresets["git-scm.com"] = "/static/icons/brand/git.svg"
	brandPresets["mercurial-scm.org"] = "/static/icons/brand/mercurial.svg"
	brandPresets["insomnia.rest"] = "/static/icons/brand/insomnia.svg"
	brandPresets["postman.com"] = "/static/icons/brand/postman.svg"
	brandPresets["swagger.io"] = "/static/icons/brand/swagger.svg"

	// ========== 安全/密码管理 ==========
	brandPresets["bitwarden.com"] = "/static/icons/brand/bitwarden.svg"
	brandPresets["keepassxc.org"] = "/static/icons/brand/keepassxc.svg"
	brandPresets["lastpass.com"] = "/static/icons/brand/lastpass.svg"
	brandPresets["proton.me"] = "/static/icons/brand/protonmail.svg"
	brandPresets["protonmail.com"] = "/static/icons/brand/protonmail.svg"
	brandPresets["protonvpn.com"] = "/static/icons/brand/protonmail.svg"

	// ========== 域名/网络 ==========
	brandPresets["godaddy.com"] = "/static/icons/brand/godaddy.svg"
	brandPresets["namecheap.com"] = "/static/icons/brand/namecheap.svg"

	// ========== 监控/日志 ==========
	brandPresets["datadoghq.com"] = "/static/icons/brand/datadog.svg"
	brandPresets["datadog.com"] = "/static/icons/brand/datadog.svg"
	brandPresets["newrelic.com"] = "/static/icons/brand/newrelic.svg"
	brandPresets["sentry.io"] = "/static/icons/brand/sentry.svg"
	brandPresets["splunk.com"] = "/static/icons/brand/splunk.svg"

	// ========== 云服务 ==========
	brandPresets["cloud.google.com"] = "/static/icons/brand/googlecloud.svg"
	brandPresets["console.cloud.google.com"] = "/static/icons/brand/googlecloud.svg"
	brandPresets["gcp.com"] = "/static/icons/brand/googlecloud.svg"
	brandPresets["mail.google.com"] = "/static/icons/brand/gmail.svg"
	brandPresets["gmail.com"] = "/static/icons/brand/gmail.svg"
	brandPresets["googlemail.com"] = "/static/icons/brand/gmail.svg"
	brandPresets["drive.google.com"] = "/static/icons/brand/googledrive.svg"
	brandPresets["calendar.google.com"] = "/static/icons/brand/googlecalendar.svg"
	brandPresets["oracle.com"] = "/static/icons/brand/oracle.svg"
	brandPresets["cloud.oracle.com"] = "/static/icons/brand/oracle.svg"
	brandPresets["blender.org"] = "/static/icons/brand/blender.svg"
	brandPresets["vitess.io"] = "/static/icons/brand/vitess.svg"

	// ========== 自托管服务 ==========
	brandPresets["caddyserver.com"] = "/static/icons/brand/caddy.svg"
	brandPresets["drone.io"] = "/static/icons/brand/drone.svg"
	brandPresets["drone.github.io"] = "/static/icons/brand/drone.svg"
	brandPresets["emby.media"] = "/static/icons/brand/emby.svg"
	brandPresets["gitea.io"] = "/static/icons/brand/gitea.svg"
	brandPresets["gitea.com"] = "/static/icons/brand/gitea.svg"
	brandPresets["try.gitea.io"] = "/static/icons/brand/gitea.svg"
	brandPresets["heimdall.site"] = "/static/icons/brand/heimdall.png"
	brandPresets["home-assistant.io"] = "/static/icons/brand/homeassistant.svg"
	brandPresets["hass.io"] = "/static/icons/brand/homeassistant.svg"
	brandPresets["homeassistant.local"] = "/static/icons/brand/homeassistant.svg"
	brandPresets["gethomepage.dev"] = "/static/icons/brand/homepage.svg"
	brandPresets["homepage.test"] = "/static/icons/brand/homepage.svg"
	brandPresets["homarr.dev"] = "/static/icons/brand/homarr.svg"
	brandPresets["jellyfin.org"] = "/static/icons/brand/jellyfin.svg"
	brandPresets["nextcloud.com"] = "/static/icons/brand/nextcloud.svg"
	brandPresets["nextcloud.local"] = "/static/icons/brand/nextcloud.svg"
	brandPresets["cloud.nextcloud.com"] = "/static/icons/brand/nextcloud.svg"
	brandPresets["openmediavault.org"] = "/static/icons/brand/openmediavault.svg"
	brandPresets["owncloud.com"] = "/static/icons/brand/owncloud.svg"
	brandPresets["owncloud.org"] = "/static/icons/brand/owncloud.svg"
	brandPresets["plex.tv"] = "/static/icons/brand/plex.svg"
	brandPresets["app.plex.tv"] = "/static/icons/brand/plex.svg"
	brandPresets["portainer.io"] = "/static/icons/brand/portainer.svg"
	brandPresets["portainer.business"] = "/static/icons/brand/portainer.svg"
	brandPresets["radarr.video"] = "/static/icons/brand/radarr.svg"
	brandPresets["sonarr.tv"] = "/static/icons/brand/sonarr.svg"
	brandPresets["traefik.io"] = "/static/icons/brand/traefik.svg"
	brandPresets["traefik.local"] = "/static/icons/brand/traefik.svg"
	brandPresets["truenas.com"] = "/static/icons/brand/truenas.svg"
	brandPresets["freenas.org"] = "/static/icons/brand/truenas.svg"
	brandPresets["unraid.net"] = "/static/icons/brand/unraid.svg"
	brandPresets["unraid.local"] = "/static/icons/brand/unraid.svg"
	brandPresets["vaultwarden.com"] = "/static/icons/brand/vaultwarden.svg"
	brandPresets["vaultwarden.local"] = "/static/icons/brand/vaultwarden.svg"
}

// MatchBrandPreset 尝试将 URL 匹配到品牌预设图标。
// 解析 URL 提取主机名，然后从最具体到最不具体逐级匹配域名。
// 例如对于 "www.jd.com"，依次尝试 "www.jd.com"、"jd.com"。
// 返回匹配的图标路径，未匹配则返回空字符串。
func MatchBrandPreset(rawURL string) string {
	normalized := normalizeURL(rawURL)
	parsed, err := url.Parse(normalized)
	if err != nil {
		return ""
	}
	hostname := strings.ToLower(parsed.Hostname())
	if hostname == "" {
		return ""
	}

	// 从最具体的域名逐级尝试匹配
	parts := strings.Split(hostname, ".")
	for i := 0; i < len(parts); i++ {
		domain := strings.Join(parts[i:], ".")
		if icon, ok := brandPresets[domain]; ok {
			return icon
		}
	}
	return ""
}
